[project]
name = "comfyui-artius-browser"
description = "Timesaver Artius Browser: lightweight asset browser for modern ComfyUI workflows."
version = "0.6"
requires-python = ">=3.10"
license = { file = "LICENSE.txt" }
dependencies = [
    "blake3>=1.0.5",
    "send2trash>=1.8.3",
]

[project.urls]
Repository = "https://github.com/AlexYez/comfyui-artius-browser"

[tool.comfy]
PublisherId = "timesaver"
DisplayName = "Timesaver Artius Browser"
Icon = "https://raw.githubusercontent.com/AlexYez/comfyui-artius-browser/refs/heads/main/icon.png"
